general {
  hide_cursor = true
}

background {
  monitor = 
  path = $HOME/stuff/pics/wallpaper/SAW.png
}

label {
  monitor =
  text = cmd[update:1000] echo "<span>$(date +"%I:%M")</span>"
  color = rgba(224, 222, 244, 1)
  font_size = 200
  font_family = JetBrainsMono Nerd Font ExtraBold
  position = 0, 250
  halign = center
  valign = center
}

label {
  monitor = 
  text = cmd[update:1000] echo "<span>$(date +"%d %B")</span>"
  color = rgba(224, 222, 244, 1)
  font_size = 50 
  font_family = JetBrainsMono Nerd Font ExtraBold
  position = 0, 100
  halign = center
  valign = center
}

input-field {
  monitor =
  size = 500, 50
  rounding = 0
  outline_thickness = 3
  dots_size = 0.3
  dots_spacing = 0.3
  dots_center = true
  outer_color = rgb(25, 23, 36)
  inner_color = rgb(224, 222, 244)
  font_color = rgb(25, 23, 36)
  fade_on_empty = false
  font_family = JetBrainsMono Nerd Font Bold
  placeholder_text = <span foreground="##191724ff">Password</span>
  hide_input = false
  position = 0, 200
  halign = center
  valign = bottom
}
